language: node_js

node_js:
    - "4.1"

install:
    - wget -O cdb.tar.gz https://connectordb.io/download/connectordb_server_current_linux_amd64.tar.gz
    - mkdir bin
    - tar xvzf cdb.tar.gz --strip 1 -C ./bin
    - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH

before_script:
    - connectordb create testdb --test
    - connectordb -l=ERROR start testdb

script:
    - npm install
    - npm run build
    - npm run check

after_success:
    - connectordb stop testdb