language: node_js

node_js:
    - "4.1"

install:
    - wget -O cdb.tar.gz https://github.com/connectordb/connectordb/releases/download/v0.3.0a1/connectordb0.3.0a1.tar.gz
    - tar xvzf cdb.tar.gz
    - export PATH=$TRAVIS_BUILD_DIR/bin:$PATH

before_script:
    - connectordb create testdb --test
    - connectordb start testdb
    - connectordb -l=ERROR run testdb &

script:
    - npm install
    - npm run build
    - npm run check
